apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: ft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      restartPolicy: Always
      containers:
      - name: kafka
        image: wurstmeister/kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-server"
        #- name: KAFKA_CREATE_TOPICS
        #  value: "user-activity-log:1:1"
        - name: HOSTNAME_COMMAND
          value: "ifconfig eth0 | grep 'inet addr' | awk '{ print $2}' | awk -F: '{print $2}'"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://_{HOSTNAME_COMMAND}:9092"
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: log-volume
          mountPath: /var/run/docker.sock
      volumes:
        - name: log-volume
          hostPath:
            path: /tmp/kafka_docker
      