apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: ft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      restartPolicy: Always
      containers:
      - name: zookeeper
        image: zookeeper
        ports:
        - containerPort: 2181
      